#!/usr/bin/env bash
# Build the Swift package of the Xchonnect core for iOS wallets into target/swift/:
#
#   target/swift/
#     Package.swift                      SwiftPM manifest (binary target + sources)
#     Sources/Xchonnect/Xchonnect.swift  generated UniFFI bindings
#     XchonnectFFI.xcframework           static libs: iOS device + iOS simulator
#
# Requirements: the Rust targets from rust-toolchain.toml (aarch64-apple-ios,
# aarch64-apple-ios-sim) and Xcode (xcodebuild). Without xcodebuild the Swift sources,
# headers and static libraries are still produced and the XCFramework step is skipped.
#
# Environment:
#   XCHONNECT_UNIFFI_FEATURES  extra cargo features (e.g. "test-helpers"; never in releases)
#   XCHONNECT_SWIFT_OUT        output directory (default target/swift)
#   XCHONNECT_PROFILE          cargo profile (default release)
set -euo pipefail
cd "$(dirname "$0")/.."

OUT=${XCHONNECT_SWIFT_OUT:-target/swift}
PROFILE=${XCHONNECT_PROFILE:-release}
FEATURES=${XCHONNECT_UNIFFI_FEATURES:-}
TARGETS=(aarch64-apple-ios aarch64-apple-ios-sim)
LIB=libxchonnect_uniffi

feature_args=()
if [ -n "$FEATURES" ]; then feature_args=(--features "$FEATURES"); fi

echo "==> building static libraries (${TARGETS[*]})"
for t in "${TARGETS[@]}"; do
  cargo build -p xchonnect-uniffi --lib --locked --profile "$PROFILE" --target "$t" ${feature_args[@]+"${feature_args[@]}"}
done

# Bindings are generated from a host build of the same crate and features: the
# interface metadata is target-independent.
echo "==> generating Swift bindings"
cargo build -p xchonnect-uniffi --lib --locked --profile "$PROFILE" ${feature_args[@]+"${feature_args[@]}"}
profile_dir=$PROFILE
if [ "$PROFILE" = "dev" ]; then profile_dir=debug; fi
host_lib="target/${profile_dir}/${LIB}.a"

rm -rf "$OUT"
gen="$OUT/.gen"
mkdir -p "$gen" "$OUT/Sources/Xchonnect" "$OUT/include"
./scripts/uniffi-bindgen.sh generate --library "$host_lib" --language swift --out-dir "$gen" --no-format
mv "$gen/Xchonnect.swift" "$OUT/Sources/Xchonnect/"
mv "$gen/XchonnectFFI.h" "$OUT/include/"
# XCFramework headers need the canonical module map name.
mv "$gen/XchonnectFFI.modulemap" "$OUT/include/module.modulemap"
rm -rf "$gen"

if ! command -v xcodebuild >/dev/null 2>&1 || ! xcodebuild -version >/dev/null 2>&1; then
  echo "xcodebuild not available: skipping the XCFramework. Static libraries:" >&2
  for t in "${TARGETS[@]}"; do echo "  target/$t/${profile_dir}/${LIB}.a" >&2; done
  echo "Run on a Mac with Xcode to finish (xcodebuild -create-xcframework)." >&2
  exit 0
fi

echo "==> creating XchonnectFFI.xcframework"
xc_args=()
for t in "${TARGETS[@]}"; do
  xc_args+=(-library "target/$t/${profile_dir}/${LIB}.a" -headers "$OUT/include")
done
xcodebuild -create-xcframework "${xc_args[@]}" -output "$OUT/XchonnectFFI.xcframework" >/dev/null

cat > "$OUT/Package.swift" <<'SWIFT'
// swift-tools-version:5.9
// Generated by scripts/build-swift.sh. Do not edit.
import PackageDescription

let package = Package(
    name: "Xchonnect",
    platforms: [.iOS(.v15)],
    products: [.library(name: "Xchonnect", targets: ["Xchonnect"])],
    targets: [
        .binaryTarget(name: "XchonnectFFI", path: "XchonnectFFI.xcframework"),
        .target(name: "Xchonnect", dependencies: ["XchonnectFFI"], path: "Sources/Xchonnect"),
    ]
)
SWIFT

for t in "${TARGETS[@]}"; do
  size=$(wc -c < "target/$t/${profile_dir}/${LIB}.a" | tr -d ' ')
  echo "$t: ${size} bytes (static, before app linking/stripping)"
done
echo "==> done: $OUT"
